name: MailImprove
favicon: null
layout_spectrum: 0.020487993489950895
typography_spectrum: 0.4431839652825147
title: Email MarketingPRO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bf1e2d'
    - '#f7941e'
    - '#f3911d'
    - '#bb1122'
  brandStrength: 0.47378028300590813
  lightness: 0.19758427189663053
  saturation: 0.3318816898390651
  rhythmicContrast: 0.8266309001483023
purpose: []
